package fr.enova.smart.home;

import fr.enova.smart.home.bean.event.Event
import fr.enova.smart.home.bean.event.TemperatureEvent
import fr.enova.smart.home.bean.event.RoomEnum
import fr.enova.smart.home.bean.command.StopVmcAction
import fr.enova.smart.home.bean.command.StartVmcAction

declare TemperatureEvent
    @role( event )
    @timestamp ( eventTimestamp )
end

rule "RG_CLEAN_EVENT"
when
    $event: Event()
    $otherEvent: Event( roomName == $event.roomName, eventTimestamp > $event.eventTimestamp )
then
    retract($event)
end


rule "RG_STOP_VMC_GAME"
when
   TemperatureEvent( roomName == RoomEnum.LIVING, value < 20.5 )
then
    channels["command"].send( new StopVmcAction() );
end


rule "RG_START_VMC_GAME"
when
   TemperatureEvent(roomName == RoomEnum.LIVING, value > 20.5)
then
    channels["command"].send( new StopVmcAction() );
end
